#!/bin/bash

INPUTFILE="$1"

test -n "$INPUTFILE" && test -x "$INPUTFILE" || ( \
	echo "You must specify an executable file as input." 1>&2; false) || exit 1

( file "$INPUTFILE" | grep 'ELF.*exec.*dynamic' >/dev/null ) || \
	( echo "Not a dynamically linked executable." 1>&2; exit 0)

LD_TRACE_LOADED_OBJECTS=1 "$1" 2>&1 | grep '=>' | grep -v 'linux-vdso' | \
sed 's/.*=> //' | tr -d '()' | \
tr -s '[:blank:]' '\t' | \
while read obj addr; do
	echo "$obj"$'\t'"${addr}"
done
echo $(readlink -f "$1")$'\t'0x0
