case_name := $(notdir $(realpath $(dir $(realpath $(lastword $(MAKEFILE_LIST))))))
CASES_c := $(CASES_c) $(case_name)
CASES_CONFIG_x := $(CASES_CONFIG_x) $(case_name)
case_name := $(call get_case_name)
$(call set_frontend_for_case,$(case_name),c)
$(call set_configs_for_case,$(case_name),x b pb mb fb Pb Mb Fb)
