THIS_MAKEFILE := $(realpath $(lastword $(MAKEFILE_LIST)))
$(warning THIS_MAKEFILE is $(THIS_MAKEFILE))

CXX := $(dirname $(THIS_MAKEFILE)/../bin/crunchc++

# CXXFLAGS += -save-temps 
CXXFLAGS += -std=c++11 # -include checked_cast.hpp

default: hello/hello


